import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const app = readFileSync('src/App.svelte', 'utf8');
const browse = readFileSync('src/panels/Browse.svelte', 'utf8');
const concepts = readFileSync('src/panels/Concepts.svelte', 'utf8');
const generate = readFileSync('src/panels/Generate.svelte', 'utf8');
const importPanel = readFileSync('src/panels/Import.svelte', 'utf8');
const notebook = readFileSync('src/panels/Notebook.svelte', 'utf8');
const mindmap = readFileSync('src/panels/Mindmap.svelte', 'utf8');
const review = readFileSync('src/panels/Review.svelte', 'utf8');
const diagnostics = readFileSync('src/panels/Diagnostics.svelte', 'utf8');
const settings = readFileSync('src/panels/Settings.svelte', 'utf8');
const sourcePicker = readFileSync('src/panels/SourcePicker.svelte', 'utf8');
const stats = readFileSync('src/panels/Stats.svelte', 'utf8');
const models = readFileSync('src/panels/Models.svelte', 'utf8');
const sourcesSvelte = readFileSync('src/panels/SourcePicker.svelte', 'utf8');
const srsTs = readFileSync('src/libs/srs.ts', 'utf8');
const typesTs = readFileSync('src/libs/types.ts', 'utf8');
const storeTs = readFileSync('src/libs/srs/sm2.ts', 'utf8');
const zhCN = JSON.parse(readFileSync('public/i18n/zh_CN.json', 'utf8'));
const enUS = JSON.parse(readFileSync('public/i18n/en_US.json', 'utf8'));

assert.match(app, /let conceptSourceTargetSeq = 0;/, 'Notebook to Concepts handoff should have an activation sequence');
assert.match(app, /conceptSourceTargetSeq \+= 1;/, 'Notebook to Concepts handoff should increment activation sequence');
assert.match(app, /key: `\$\{request\.key\}#\$\{conceptSourceTargetSeq\}`/, 'Repeated same-source handoffs should create a fresh target key');
assert.match(app, /<Notebook[^>]+sourceTarget=\{notebookTarget\}[^>]+openConceptsFromNotebook/, 'Notebook panel should receive source handoff callbacks');
assert.match(app, /<Concepts[^>]+notebookTarget=\{conceptSourceTarget\}/, 'Concepts panel should receive Notebook concept targets');
assert.match(app, /<Mindmap[^>]+\{jumpTarget\}/, 'Mindmap panel should receive jump targets');
assert.match(app, /<Diagnostics[^>]+\{conceptStore\}[^>]+\{mindmapStore\}/, 'Diagnostics panel should receive concept and mindmap stores');
assert.match(app, /<Import[^>]+\{plugin\}[^>]+\{cardStore\}[^>]+\{conceptStore\}[^>]+\{mindmapStore\}/, 'Import panel should receive plugin and stores for compatible export');
assert.match(app, /function openImportPanel\(\)/, 'App should expose a Stats to Import handoff');
assert.match(app, /<Stats[^>]+\{cardStore\}[^>]+\{openImportPanel\}/, 'Stats panel should receive the Import handoff callback');
assert.match(app, /function openConceptsPanel\(\)/, 'App should expose a Quick Cards to Graph Generate handoff');
assert.match(app, /<Generate[^>]+\{plugin\}[^>]+\{cardStore\}[^>]+\{config\}[^>]+\{openConceptsPanel\}/, 'Generate panel should receive the graph workflow callback');
assert.match(app, /let reviewQueue:/, 'App should hold a temporary filtered review queue');
assert.match(app, /function startFilteredReview\(ids: string\[\]/, 'App should expose filtered review handoff');
assert.match(app, /<Review[^>]+queue=\{reviewQueue\}/, 'Review panel should receive filtered review queues');
assert.match(app, /<Browse[^>]+\{startFilteredReview\}/, 'Browse panel should be able to start filtered review');
assert.match(app, /label: '制卡'/, 'Quick card tab should not be labeled as the main generation workflow');
assert.match(app, /label: '图谱生成'/, 'Concepts tab should be labeled as the primary graph generation workflow');

const tabIds = [...app.matchAll(/\{\s*id: '([^']+)', label:/g)].map((match) => match[1]);
for (const id of tabIds) {
  assert.ok(zhCN[`${id}Tab`], `zh_CN i18n should define ${id}Tab`);
  assert.ok(enUS[`${id}Tab`], `en_US i18n should define ${id}Tab`);
}

assert.match(notebook, /openConceptsFromNotebook/, 'Notebook should expose a send-to-concepts action');
assert.match(notebook, /buildNotebookConceptRequest/, 'Notebook should build scoped concept requests');
assert.match(notebook, /noteIds/, 'Notebook chat context should include selected notes');
assert.match(notebook, /noteModes/, 'Notebook concept handoff should include selected notes');
assert.match(notebook, /sourceModes/, 'Notebook chat context should preserve selected source modes');
assert.match(notebook, /renderMath\(msgListEl\)/, 'Notebook chat should render math formulas in messages');
assert.match(notebook, /nb-ctx-chip/, 'Notebook context indicator should use SiYuan-style chips');
assert.match(notebook, /#iconFiles/, 'Notebook context indicator should use SiYuan file icon');
assert.match(notebook, /nb-session-del[\s\S]*#iconClose/, 'Notebook session removal should use a SiYuan close icon');
assert.match(notebook, /nb-icon-button/, 'Notebook toolbar actions should use icon buttons');
assert.doesNotMatch(notebook, /📄|💡|🔤|>×<\/button>|>✕<\/button>/, 'Notebook should avoid emoji counters and symbol-only removal buttons');
assert.match(concepts, /applyNotebookTarget\(notebookTarget\)/, 'Concepts should react to Notebook targets');
assert.match(concepts, /collectPipelineSources/, 'Concepts should collect all source types through SourceHub');
assert.match(concepts, /OpenNotebookClient/, 'Concepts should load OpenNotebook sources directly');
assert.match(concepts, /toggleOpenNotebookSource/, 'Concepts should let users add OpenNotebook sources in the graph workflow');
assert.match(concepts, /notebook-source-results/, 'Concepts should display selectable OpenNotebook source rows');
assert.match(concepts, /sourceMode: 'manual' \| 'opennotebook' \| 'mixed'/, 'Concepts should support mixed source mode');
assert.match(concepts, /searchSiyuanDocs/, 'Concepts should search SiYuan docs for mixed sources');
assert.match(concepts, /siyuanDocs: selectedSiyuanDocs/, 'Concepts should pass selected SiYuan docs into SourceHub');
assert.match(concepts, /localFiles,/, 'Concepts should pass selected local text files into SourceHub');
assert.match(concepts, /openNotebookSearchType: 'text'/, 'Concepts should avoid default vector search failures in OpenNotebook');
assert.match(concepts, /accept="\.txt,\.md,\.markdown,\.html,\.htm,text\/plain,text\/markdown,text\/html"/, 'Concepts should accept lightweight local text and HTML files');
assert.match(concepts, /local-file-picker[\s\S]*#iconUpload/, 'Concepts local file picker should use a SiYuan upload icon');
assert.match(concepts, /buildPipelineSources/, 'Concepts should merge selected source types before running the pipeline');
assert.match(concepts, /bind:value=\{concept\.title\}/, 'Concept candidates should be editable before confirmation');
assert.match(concepts, /bind:value=\{relation\.fromTempId\}/, 'Relation endpoints should be editable before confirmation');
assert.match(concepts, /bind:value=\{card\.conceptTempId\}/, 'Card-to-concept assignment should be editable before confirmation');
assert.match(concepts, /bind:value=\{card\.front\}/, 'Card fronts should be editable before confirmation');
assert.match(concepts, /notebookNoteIds/, 'Concepts should preserve Notebook note scope');
assert.match(concepts, /notebookNoteIds,/, 'Concepts should pass note scope into SourceHub');
assert.match(concepts, /confirmPipelineResult/, 'Concepts should confirm candidates into stores');
assert.match(concepts, /syncConceptMindmap/, 'Concept confirmation should sync a concept mindmap');
assert.match(concepts, /renderMath\(candidateReviewEl\)/, 'Concept candidates should render math formulas before confirmation');
assert.match(concepts, /来源制卡与图谱/, 'Concepts should present the source-to-cards-and-graph workflow as the primary generation path');
assert.match(concepts, /@media \(max-width: 1200px\)[\s\S]*\.candidate-columns[\s\S]*grid-template-columns: 1fr/, 'Concept candidate columns should collapse before narrow SiYuan panes become cramped');
assert.match(concepts, /@media \(max-width: 900px\)[\s\S]*\.candidate-line[\s\S]*flex-direction: column/, 'Concept candidate editors should stack fields on narrow panes');
assert.match(concepts, /siyuan-chip[\s\S]*#iconClose/, 'Concept selected source chips should use SiYuan close icons');
assert.match(concepts, /\.concept-panel[\s\S]*overflow-y: auto/, 'Concepts panel should scroll instead of clipping source and candidate controls');
assert.doesNotMatch(concepts, />×<\/button>|>✕<\/button>/, 'Concepts should avoid symbol-only removal buttons');
assert.match(browse, /openConceptMindmapForCard/, 'Browse should let a card open or create its concept mindmap');
assert.match(browse, /reviewFilteredCards/, 'Browse should let filtered or selected cards become a review queue');
assert.match(browse, /复习筛选/, 'Browse should expose a filtered review action');
assert.match(browse, /复习选中/, 'Browse should expose a selected-card review action');
assert.match(browse, /browse-review-button[\s\S]*#iconRefresh/, 'Browse filtered review should use a SiYuan refresh icon');
assert.match(browse, /syncConceptMindmap/, 'Browse card details should be able to sync a concept mindmap');
assert.match(browse, /getLinkedMindmaps/, 'Browse should list mindmaps linked to a card');
assert.match(mindmap, /mode: 'cards' \| 'doc' \| 'concepts'/, 'Mindmap should keep cards/doc/concepts modes');
assert.match(mindmap, /loadConceptMindmap/, 'Mindmap should generate from concept graph');
assert.match(mindmap, /generateCardsFromCurrentMindmap/, 'Mindmap should generate flashcards from the current map');
assert.match(mindmap, /linkedCardIds/, 'Mindmap-generated cards should be linked back to the map');
assert.match(mindmap, /卡片 → 导图/, 'Mindmap should label the cards-to-map path explicitly');
assert.match(mindmap, /来源 → 导图/, 'Mindmap should label the source-to-map path explicitly');
assert.match(mindmap, /图谱 → 导图/, 'Mindmap should label the graph-to-map path explicitly');
assert.match(mindmap, /导图 → 卡片/, 'Mindmap should label the map-to-cards path explicitly');
assert.match(mindmap, /renderMath\(reviewDialogEl\)/, 'Mindmap review overlay should render math formulas');
assert.match(mindmap, /import \{ createCard, scheduleCard \} from '..\/libs\/srs';/, 'Mindmap review overlay should use the scheduler facade');
assert.match(mindmap, /scheduleCard\(grade, \{ \.\.\.reviewCard \}, cfg\.scheduler \|\| 'sm2'\)/, 'Mindmap grading should honor the configured scheduler');
assert.match(mindmap, /getMindmapSourceMeta/, 'Mindmap saved-list entries should expose source type labels');
assert.match(mindmap, /mindmap-icon-button/, 'Mindmap toolbar actions should use SiYuan-style icon buttons');
assert.match(mindmap, /#iconFiles/, 'Mindmap document rows should use SiYuan file icon');
assert.match(mindmap, /fitMarkmapWithProfile/, 'Mindmap should fit large maps using profile-aware tuning');
assert.match(mindmap, /sizeProfile: currentProfile/, 'Mindmap renderer should receive the size profile');
assert.match(mindmap, /mindmap-canvas--large/, 'Mindmap canvas should expose a large-map class');
assert.match(mindmap, /searchMindmapNodes/, 'Mindmap should search nodes through the markmap data tree');
assert.match(mindmap, /focusMindmapSearchMatch/, 'Mindmap search should focus matches through markmap APIs');
assert.match(mindmap, /mindmap-searchbar/, 'Mindmap should expose a compact node search bar');
assert.match(mindmap, /查找节点、路径或卡片 ID/, 'Mindmap search should support node, path and card id queries');
assert.match(mindmap, /filterMindmapMarkdown/, 'Mindmap should filter rendered markdown without mutating saved maps');
assert.match(mindmap, /mindmapViewMode/, 'Mindmap should keep a view mode for large-map filtering');
assert.match(mindmap, /全部[\s\S]*有卡[\s\S]*缺卡[\s\S]*邻域/, 'Mindmap should expose all/card/gap/neighborhood views');
assert.match(mindmap, /显示 \{currentViewStats\.visibleNodes\} \/ \{currentViewStats\.totalNodes\} 个节点/, 'Mindmap filtered views should show visible node counts');
assert.match(mindmap, /generateCardsFromGaps/, 'Mindmap should generate candidate cards from gap leaf nodes');
assert.match(mindmap, /gapNodesToSourceText/, 'Mindmap should convert gap nodes to pipeline source text');
assert.match(mindmap, /从缺卡生成候选/, 'Mindmap gap view should expose a generate-cards-from-gaps button');
assert.match(mindmap, /openConceptsFromMindmapGaps/, 'Mindmap should receive the gap-to-concepts handoff callback');
assert.match(concepts, /applyMindmapGapTarget\(mindmapGapTarget\)/, 'Concepts should react to mindmap gap targets');
assert.match(concepts, /sourceMode = 'manual'/, 'Concepts should switch to manual mode for gap content');
assert.match(concepts, /hasOpenNotebook/, 'Concepts should detect whether OpenNotebook endpoint is configured');
assert.match(concepts, /!hasOpenNotebook && sourceMode !== 'manual'/, 'Concepts should force manual mode when OpenNotebook is unavailable');
assert.match(concepts, /手动 \+ 文档/, 'Concepts should expose an offline-friendly hybrid source mode');
assert.match(concepts, /cdfMode/, 'Concepts should support CDF descriptor-based card generation');
assert.match(concepts, /CDF 维度制卡/, 'Concepts CDF toggle should have a visible label');
assert.match(typesTs, /drill/, 'CardStatus should include drill status for low-score mechanical practice');
assert.match(srsTs, /consecutiveLapses/, 'SRS should track consecutive lapses for drill entry');
assert.match(srsTs, /status = 'drill'/, 'SRS should set card to drill status after consecutive failures');
assert.ok(srsTs.includes("card.status === 'drill'"), 'Drill cards should always be considered due');
// Mobile responsiveness: at least 3 panels should have @media breakpoints and UI components should use min-width:0 to prevent overflow
const responsivePanels = [concepts, generate, importPanel, stats].filter((panelText) => /@media/.test(panelText));
assert.ok(responsivePanels.length >= 3, `At least 3 panels should have @media responsive breakpoints; found ${responsivePanels.length}`);
const panelsWithMinWidthZero = [concepts, browse, importPanel, mindmap, notebook, review, diagnostics, settings, models, sourcesSvelte, stats]
    .filter((panelText) => /min-width:\s*0/.test(panelText));
assert.ok(panelsWithMinWidthZero.length >= 5, `${panelsWithMinWidthZero.length} panels should use min-width: 0 to prevent overflow in narrow viewports`);
assert.match(app, /openConceptsFromMindmapGaps/, 'App should expose a gap-to-concepts handoff function');
assert.match(app, /mindmapGapTarget/, 'App should hold a mindmap gap target signal');
assert.doesNotMatch(mindmap, /📋|🎴|📄|📝|🔄|💡|❌|✅|⚠️/, 'Mindmap panel should avoid emoji controls and status text');
assert.match(importPanel, /buildExportPayload/, 'Import panel should use the shared export payload builder');
assert.match(importPanel, /saveToSiyuan/, 'Import panel should export selected backup content to SiYuan documents');
assert.match(importPanel, /exportIncludeCards/, 'Import panel should let users choose which content to export');
assert.match(importPanel, /export-scope/, 'Import panel should render export scope controls');
assert.match(importPanel, /parsePluginImport/, 'Import panel should restore plugin-native backup files');
assert.match(importPanel, /conceptStore\.importGraph/, 'Import panel should restore concept graph data');
assert.match(importPanel, /mindmapStore\.importMindmaps/, 'Import panel should restore saved mindmaps');
assert.match(importPanel, /accept="\.apkg,\.txt,\.csv,\.json,\.md,\.markdown"/, 'Import panel should accept plugin backup files');
assert.match(importPanel, /conceptStore\?\.getAll/, 'Export should include concept graph nodes');
assert.match(importPanel, /mindmapStore\?\.getAll/, 'Export should include saved mindmaps');
assert.match(importPanel, /syncCardsToSiyuanRiff/, 'Import panel should expose guarded sync to SiYuan native flashcards');
assert.match(importPanel, /confirm\(\s*'同步到思源闪卡'/, 'Riff sync should require an explicit confirmation');
assert.match(importPanel, /riffDeckName/, 'Riff sync should let users choose a target deck name');
assert.match(importPanel, /riffMaxCards/, 'Riff sync should limit batch size');
assert.match(importPanel, /loadData\?\.\('riff-sync'\)/, 'Riff sync should load persisted sync records before writing');
assert.match(importPanel, /saveData\?\.\('riff-sync'/, 'Riff sync should persist card-to-block sync records');
assert.match(importPanel, /skippedCardIds/, 'Riff sync UI should report skipped already-synced cards');
assert.match(importPanel, /updatedBlockIds/, 'Riff sync UI should report updated stale synced cards');
assert.match(importPanel, /riffSyncRecordCount/, 'Import panel should show local Riff sync record count');
assert.match(importPanel, /auditRiffSyncProjection/, 'Import panel should audit Riff projection status before syncing');
assert.match(importPanel, /riffAudit\.fresh/, 'Riff audit should show fresh synced cards');
assert.match(importPanel, /riffAudit\.stale/, 'Riff audit should show stale synced cards');
assert.match(importPanel, /riffAudit\.unsynced/, 'Riff audit should show unsynced cards');
assert.match(importPanel, /riffAudit\.orphanRecords/, 'Riff audit should show orphan local records');
assert.match(importPanel, /riff-audit-list/, 'Import panel should preview cards that need Riff projection attention');
assert.match(importPanel, /resetRiffSyncState/, 'Import panel should let users clear local Riff sync records');
assert.match(importPanel, /confirm\(\s*'重置同步状态'/, 'Clearing Riff sync records should require confirmation');
assert.match(importPanel, /清除记录/, 'Riff sync local records should be clearable from the UI');
assert.doesNotMatch(importPanel, /📌|❌|✅|↩|⊘|✕/, 'Import panel should avoid emoji-like controls and status text');
assert.match(generate, /gen-status--\{aiStatusKind\}/, 'Generate status should use semantic state classes');
assert.match(generate, /openConceptsPanel/, 'Generate panel should link to the graph generation workflow');
assert.match(generate, /gen-workflow-note/, 'Generate panel should explain quick-card versus graph workflow');
assert.match(generate, /来源制卡与图谱/, 'Quick card panel should hand off to the source-to-graph workflow');
assert.match(generate, /#iconGraph/, 'Generate graph handoff should use a SiYuan graph icon');
assert.match(generate, /语言：\{selectedAgent\.language\}/, 'Generate agent metadata should use text labels instead of emoji');
assert.match(generate, /#iconClose/, 'Generate preview delete should use a SiYuan icon button');
assert.doesNotMatch(generate, /📝|🌐|🎯|❌|✅|✕/, 'Generate panel should avoid emoji and symbol-only controls');
assert.match(stats, /openImportPanel/, 'Stats should link to the canonical Import panel');
assert.doesNotMatch(stats, /importCards|exportCards|clearAll|cardStore\.clear|cardStore\.importCards|cardStore\.exportCards|confirm\(/, 'Stats should not duplicate data import/export or destructive card clearing');
assert.doesNotMatch(browse, /confirm\('⚠️'/, 'Browse delete confirmations should use text titles');
assert.match(browse, /browse-linked-map-button[\s\S]*#iconGraph/, 'Browse linked mindmaps should use a SiYuan graph icon');
assert.doesNotMatch(browse, /🧠/, 'Browse linked mindmaps should avoid emoji icons');
assert.doesNotMatch(models, /confirm\('⚠️'/, 'Models delete confirmations should use text titles');
assert.match(models, /mp-icon-button[\s\S]*#iconRefresh/, 'Models auto assignment should use a SiYuan refresh icon');
assert.doesNotMatch(models, /🔄|⚠️|✕/, 'Models panel should avoid emoji and symbol-only controls');
assert.match(sourcePicker, /#iconFiles/, 'SourcePicker document rows should use SiYuan file icon');
assert.match(sourcePicker, /source-hint--warn/, 'SourcePicker should use semantic warning styling');
assert.doesNotMatch(sourcePicker, /⚠️|📄|✅/, 'SourcePicker should avoid emoji for hints and document rows');
assert.match(diagnostics, /siyuan-all-in-one-diagnostics/, 'Diagnostics should produce structured reports');
assert.match(diagnostics, /copy-diagnostic-report/, 'Diagnostics should expose copyable reports');
assert.doesNotMatch(diagnostics, /apiKey["']?\s*:/, 'Diagnostics reports must not serialize API keys');
assert.match(diagnostics, /apiKeySet/, 'Diagnostics reports should only expose whether an API key is set');
assert.match(diagnostics, /getProviderCapabilities/, 'Diagnostics should report provider structured-output capabilities');
assert.match(diagnostics, /structuredOutputStrategy/, 'Diagnostics report should include structured-output strategy');
assert.match(diagnostics, /jsonFallbackOnUnsupported/, 'Diagnostics report should expose JSON fallback behavior');
assert.match(review, /import \{ scheduleCard \} from '..\/libs\/srs';/, 'Review should use the scheduler facade');
assert.match(review, /scheduleCard\(g, card, cfg\.scheduler \|\| 'sm2'\)/, 'Review grading should honor the configured scheduler');
assert.match(review, /export let queue:/, 'Review should accept temporary filtered queues');
assert.match(review, /activeQueueTitle/, 'Review should show when it is running a filtered queue');
assert.match(review, /返回到期复习/, 'Review should let users leave a filtered queue');
assert.match(review, /review-queue-banner/, 'Review should render filtered queue context in a compact banner');
assert.match(settings, /getProviderCapabilities/, 'Settings should expose provider structured-output capabilities');
assert.match(settings, /getProviderJsonLabel/, 'Settings should show the active JSON strategy per provider');
assert.match(settings, /let scheduler: 'sm2' \| 'fsrs' = 'sm2';/, 'Settings should keep a scheduler state');
assert.match(settings, /scheduler = config\.scheduler === 'fsrs' \? 'fsrs' : 'sm2';/, 'Settings should load the persisted scheduler safely');
assert.match(settings, /scheduler,/, 'Settings should persist the selected scheduler');
assert.match(settings, /id="settings-scheduler"/, 'Settings should expose a scheduler selector');
assert.match(settings, /value="sm2"[\s\S]*SM-2/, 'Settings should keep SM-2 available as the compatible default');
assert.match(settings, /value="fsrs"[\s\S]*FSRS/, 'Settings should expose optional FSRS scheduling');
assert.match(settings, /settings-icon-button/, 'Settings actions should use SiYuan-style icon buttons');
assert.match(settings, /#iconRefresh/, 'Settings model fetch should use the SiYuan refresh icon');
assert.match(settings, /#iconClose/, 'Settings model removal should use a SiYuan close icon');
assert.doesNotMatch(settings, /🎴|🧠|🔄|⚠️|✕/, 'Settings should avoid emoji and symbol-only controls in the SiYuan-style panel');

console.log(JSON.stringify({
  appContracts: 14,
  panelContracts: 78,
  repeatedNotebookHandoff: true,
  mixedSources: true,
  tabI18n: tabIds.length,
  diagnosticsSecretsRedacted: true,
}, null, 2));
